canonicalize command path

diff --git a/job-runus b/job-runus
--- a/job-runus
+++ b/job-runus
@@ -1,6 +1,7 @@
 #!/bin/bash
 # by Robert Socha / 2021
 # version: 0.1 beta
+# URL: https://github.com/rjsocha/job-runus
 
 ME="job-runus"
 
@@ -31,34 +32,34 @@ _jobid=$(date +%s%N)
 
 if [[ -s /etc/job-runus/config ]]
 then
-	source /etc/job-runus/config
+    source /etc/job-runus/config
 fi
 
 if [[ -s ~/.config/$ME/config ]]
 then
-	source "~/.config/$ME/config"
+    source "$HOME/.config/$ME/config"
 fi
 
 __id=$(id -u)
 if [[ -z $JOB_RUNUS_LOG ]]
 then
-	if [[ ${__id} -eq 0 ]]
-	then
-		JOB_RUNUS_LOG="/var/log/$ME.log"
-	else	
-		mkdir -p "$(eval echo ~/.${ME}/)"
-		JOB_RUNUS_LOG=$(eval echo "~/.${ME}/${ME}.log")
-	fi
+    if [[ ${__id} -eq 0 ]]
+    then
+        JOB_RUNUS_LOG="/var/log/$ME.log"
+    else
+        mkdir -p "$(eval echo ~/.${ME}/)"
+        JOB_RUNUS_LOG=$(eval echo "~/.${ME}/${ME}.log")
+    fi
 fi
 
 if [[ -z $JOB_RUNUS_SPOOL ]]
 then
-	if [[ ${__id} -eq 0 ]]
-	then
-		JOB_RUNUS_SPOOL="/var/spool"
-	else	
-		JOB_RUNUS_SPOOL=$(eval echo "~/.${ME}/spool")
-	fi
+    if [[ ${__id} -eq 0 ]]
+    then
+        JOB_RUNUS_SPOOL="/var/spool"
+    else
+        JOB_RUNUS_SPOOL=$(eval echo "~/.${ME}/spool")
+    fi
 fi
 
 JSPOOL="${JOB_RUNUS_SPOOL}/$ME"
@@ -164,13 +165,15 @@ _ocmd="$1"
 # try to locate command in path
 if ! _cmd=$(command -v "$_ocmd" 2>/dev/null)
 then
-    if ! _cmd=$(readlink -e -n "$_ocmd")
-    then
-        echo "ERROR: unable to locate ${_ocmd} command..." >&2
-        exit 1
-    fi
-    echo $_cmd
+    echo "ERROR: unable to locate ${_ocmd} command..." >&2
+    exit 1
 fi
+# try to canonicalize (my be unsafe?)
+if _cmd_full=$(readlink -e -n "$_ocmd")
+then
+    command -v "${_cmd_full}" 2>/dev/null && _cmd="${_cmd_full}"
+fi
+
 shift
 if [[ $_lock -eq 1 ]]
 then
@@ -238,7 +241,7 @@ else
         (
             $_flock -n 9 || exit 255
             echo "## Start Job ${_jobname} at $(date -R) #########"
-            # Split stderr to separate files	
+            # Split stderr to separate file
             if [[ ${_noerrordump} -eq 0 ]]
             then
                 $exe $_cmd $@  2> >(tee "${_TMPFILE_ERR}")
